'use client'
import './globals.css'
import { Rubik } from 'next/font/google'
import { Provider } from 'react-redux'
import store from './redux/store'
import 'bootstrap/dist/css/bootstrap.css'
// import './i18next';
import Navigator from './components/Navigator'
import { useSelector } from 'react-redux'
const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  // const theme = useSelector(state => state.theme.theme)
  return (
    <html lang="en">
        <Provider store={store}>
      <body className={rubik.className}>
        <Navigator />
        {children}
        </body>
        </Provider>
    </html>
  )
}
